language: java 
jdk: oraclejdk8
addons:
  sonarqube: true
env:
  global:
    - secure: "di1RYHs0jHsibqeYcJcFvltUmHEzCoiqrPzVOs0IFdfCBDvv2MVb2gQ5ba4Olv08drrMRUVYAM5VCg40sIBW0ZMmCvMqFKniqemmtJ78D4+iPcYXfOLgtPQbejU4Hbbze93W/v5TsVs1R54CEKsmwgwuEcEF7E+njU+YXFSjp5yXngjrMCu3UQXQrGPklg0a2VKIx1ikZXd/rtYD5bV4OidG1nlZmGJX4CYmnSIRbWj1A64o02GyK/gsYt3iWsUWzLC08VGBqdIOj7tVwmZXIc5l3z1mJsjZ4O/E5PdpUiOd7B0hUj8ZEF9lBpPDzKZlfm8Gv/Z2j6i7rk3ddhuPOHlbyTaz86fKHQUmWslb4DcXkqFELMj5n2HLCtD0W1EYxYSI1WTK86qOM4EUco6JdjO/d5v5g1hk4OujjTc7K7Sq9KH7RHPDfmeu/SavZP7k+1yvam2qMNcH058QbWhA4zdUIbcL1728A4TujQoHf7sFH8DwyLgkEfHCI+HckqaFJ3HyNuq6LlHe2bndwl573xD7XEoDX8bslP8LILA+kPMEivL+VgvN5ZbGLu7tK2hN/19mdcyfmWh0U4mrMs9i7MykPWgFVEqtBeZwHS8IAJnHGXVdqVC5ddEi6EUHAk0/mTkLqZqsLkisklSRGKZsYCGr2DOzfRyTx0VNgsHu4R8="
script:
  - sonar-scanner -Dsonar.login=$ROGUELIKE_SONAR_TOKEN
